### ISSUE TITLE
A few EXPERIMENT_PACKAGES have no STUDY, only STUDY_REF

### ISSUE THREAD

**Issue by seandavi** [omicidx/omicidx-parsers#1]
```
2018-02-27 23:54:15,286:WARNING:Error('NoneType' object has no attribute 'attrib'): ERX1004300
2018-02-27 23:54:15,466:WARNING:Traceback (most recent call last):
  File "scripts/insert_records_to_postgresql.py", line 29, in gen
    j = s.SRAExperiment(s.load_experiment_xml_by_accession(accession).getroot())
  File "/Users/sdavis2/Documents/git/omicidx/omicidx/sra_parsers.py", line 52, in __init__
    'study': self.parse_study(node.find(".//STUDY"))
  File "/Users/sdavis2/Documents/git/omicidx/omicidx/sra_parsers.py", line 211, in parse_study
    d.update(xml.attrib)
AttributeError: 'NoneType' object has no attribute 'attrib'
```

**Comment by seandavi** [comment]
I'm not using the experiment_packages stuff anymore.
