### ISSUE TITLE
GSE24417 is a "reanalysis" series. No samples or platform entries are available

### ISSUE THREAD

**Issue by seandavi** [omicidx/omicidx-parsers#20]
```
INFO:root:Accessing accession GSE24417 in SOFT format
Traceback (most recent call last):
  File "process_geo.py", line 36, in <module>
    inserts('GSE')
  File "process_geo.py", line 27, in inserts
    rows = list(process(end_date, etyp))
  File "process_geo.py", line 12, in process
    for z in gp.geo_entity_iterator(accession, targ='self'):
  File "/private/tmp/.venv/lib/python3.7/site-packages/omicidx/geo/parser.py", line 567, in geo_entity_iterator
    yield (_parse_single_entity_soft(entity))
  File "/private/tmp/.venv/lib/python3.7/site-packages/omicidx/geo/parser.py", line 387, in _parse_single_entity_soft
    return (_parse_single_gse_soft(d2))
  File "/private/tmp/.venv/lib/python3.7/site-packages/omicidx/geo/parser.py", line 422, in _parse_single_gse_soft
    return pydantic_models.GEOSeries(**d2)
  File "/private/tmp/.venv/lib/python3.7/site-packages/pydantic/main.py", line 283, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for GEOSeries
sample_id
  field required (type=value_error.missing)
platform_id
  field required (type=value_error.missing)
```

**Comment by seandavi** [comment]
Closing as part of a pre-publication tracker cleanup (2026-05-28). Obsolete: process_geo.py no longer exists in the current package.
